name: Build, Test, and Deploy to Azure Web App (Container)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write
  actions: read

env:
  APP_PORT: 8080
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/frontendapp-node   # repo name
  AZURE_RESOURCE_GROUP: Anas-LABSs
  AZURE_WEBAPP_NAME: frontendapp-web-anas

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & test
        run: mvn -B -DskipTests=false clean package

      - name: Upload JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar
          retention-days: 14

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Point Web App to the new image + restart
        run: |
          # Ensure required app settings
          az webapp config appsettings set \
            -g "${{ env.AZURE_RESOURCE_GROUP }}" \
            -n "${{ env.AZURE_WEBAPP_NAME }}" \
            --settings WEBSITES_PORT=${{ env.APP_PORT }} \
                       DOCKER_REGISTRY_SERVER_URL=https://index.docker.io/v1/

        
          # Set the container image (SHA tag)
          az webapp config container set \
            -g "${{ env.AZURE_RESOURCE_GROUP }}" \
            -n "${{ env.AZURE_WEBAPP_NAME }}" \
            --container-image-name "${{ env.IMAGE_NAME }}:${{ github.sha }}" \
            --container-registry-url "https://index.docker.io"

          # Restart to pull now
          az webapp restart -g "${{ env.AZURE_RESOURCE_GROUP }}" -n "${{ env.AZURE_WEBAPP_NAME }}"
